export const ApiRoutes = {
  CreateBook: '/api/create-book',
  DeleteBook: '/api/delete-book',
  GetBooks: '/api/get-books',
  GetBookById: '/api/get-book-by-id',
  GetSearchResults: '/api/get-search-results',
  UpdateBook: '/api/update-book',
  CreateChapter: '/api/create-chapter',
  DeleteChapter: '/api/delete-chapter',
  UpdateChapter: '/api/update-chapter',
  CreateCharacter: '/api/create-character',
  DeleteCharacter: '/api/delete-character',
  UpdateCharacter: '/api/update-character',
  GetNotesByLabelIds: '/api/get-notes-by-label-ids',
  CreateNote: '/api/create-note',
  DeleteNote: '/api/delete-note',
  UpdateNote: '/api/update-note',
  CreateSetting: '/api/create-setting',
  DeleteSetting: '/api/delete-setting',
  UpdateSetting: '/api/update-setting',
};
